# Run docker-compose build
# Run docker-compose up
# Live long and prosper
# docker command to Run
#  Open another command window and navigate to this application's root folder in the command window
#  Run `docker-compose build` to build the images
#  Run `docker-compose up` to run the containers
version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ~/datadir/mysql:/var/lib/mysql
    ports:
      - 3306:3306 
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: abc12345
  node-app:
    build: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8080:8080
    depends_on:
      - app-mysql